KnightHacks/forge

.github/CODEOWNERS
apps/feprep/src/server/api/root.ts

Since FEPrep is currently a senior design project, only the core maintainers of FEPrep shall make changes to its code until further notice.
This PR adds a CODEOWNERS file designating the FEPrep GitHub team to be the owners of FEPrep's source code
After merging, will check if FEPrep team members are tagged as reviewers for any changes made to FEPrep

[FEPrep] Set owners of FEPrep app to FEPrep GitHub team

---

apps/feprep/package.json
apps/feprep/src/app/layout.tsx
apps/feprep/src/app/problems/[id]/_components/excalidraw-wrapper.tsx
apps/feprep/src/app/problems/[id]/page.tsx
apps/feprep/src/app/problems/page.tsx
packages/ui/package.json
packages/ui/src/tabs.tsx
pnpm-lock.yaml

Users need to be able to view individual questions.
This PR implements the problem by id page.

[FEPrep] Add problems page

---

.github/PULL_REQUEST_TEMPLATE

"<!--
Please describe the motivation for this PR."
^ This is ugly
Fixes:
"<!--
Please describe the motivation for this PR."
Will check PR template after merging

[Repo] Fix typo in PR template

---

apps/feprep/package.json
apps/feprep/src/app/problems/[id]/_components/auth-button.tsx
apps/feprep/src/app/problems/[id]/_components/navbar.tsx
apps/feprep/src/app/problems/[id]/_components/timer-button.tsx
apps/feprep/src/app/problems/[id]/_components/toggle-solution-button.tsx
apps/feprep/src/app/problems/[id]/page.tsx
apps/feprep/src/app/stores/auth/session-store-context-provider.tsx
apps/feprep/src/app/stores/auth/session-store-provider.tsx
apps/feprep/src/app/stores/auth/session-store.tsx
pnpm-lock.yaml

From lessons learned building the previous FEPrep site, we realized state management was something we should take better care of in our app. As our app became more complex, we slowly realized we were performing a lot of prop drilling to build certain features, which is why we're going to utilize Zustand + React context to create a powerful state management solution. 
This PR sets up Zustand with React context to share the current session to deeply nested client components (we'll likely encounter this later down the line implementing comments functionality).
Sign out and sign in functionality works in navbar
https://github.com/user-attachments/assets/5ee0dbf9-7305-4fcf-bcfa-0c2f7478ec69

[FEPrep] Problems page clean up

---

apps/tk/src/consts/index.ts
apps/tk/src/hooks/animals.ts
docker-compose.yml
pnpm-lock.yaml

the cat webhook (part of the animals webhook) has consistently been going off at the wrong time, and the goat command/webhook is not functional.
syncs the cat webhook to EST by added 5 hours to the cron job. also updates the goat command by adding all the linkedin profile pictures to `index.ts`. it seems like linkedin might've changed the way they use profile picture links.
wait until tomorrow to see if the cat webhook works at the right time. running `/goat` for testing goat.

Update animals + goat

---

apps/blade/package.json
packages/api/package.json
packages/api/src/env.ts
packages/api/src/router/auth.ts
packages/api/src/router/payment.ts
packages/api/src/trpc.ts
packages/consts/src/knight-hacks.ts
pnpm-lock.yaml

KH admins don't have their KH emails tied to their discord users so checking emails to verify admins is no longer sufficient.
This PR creates an Admin Procedure that checks that a discord user has a specific role before they can access certain routes
Assign yourself the blade role in the discord and then try to call the test procedure in the authRouter.

Add admin procedure

---

apps/blade/src/app/page.tsx
packages/api/src/env.ts
packages/api/src/trpc.ts
packages/consts/src/knight-hacks.ts

We're having problems building discordjs in coolify
The admin procedure now uses fetch and typecasting to verify roles instead of discordjs
Give yourself the blade role in the Knight Hacks discord and see if you can call the admin message in the auth router.

Fix admin procedure

---

pnpm-lock.yaml

Coolify deployments were failing due to the pnpm-lock-file being out of sync with the package.json file. 
pnpm-lock.yml packages are synced with package.json.
Manual testing
Ran the changes locally and it works.

synced pnpm-lock.yml with package.json

---

apps/blade/src/app/admin/events/_components/events-table.tsx
apps/blade/src/app/dashboard/_components/member-dashboard/member-dashboard.tsx
packages/api/src/routers/event.ts
packages/api/src/routers/member.ts
packages/db/src/index.ts
packages/db/src/schemas/knight-hacks.ts

When events are fetched per member the events don't have a numAttended field. On top of this there shouldn't be a set numAttended field on events or Members as those should be initialized upon selection
Fixed the getMembers query and removed numAttended from events

Fix event querying and schema

---

apps/blade/src/app/settings/member-profile-form.tsx

Form doesn't update
Adds discordUser to default values
Update your form with local changes

discord quick fix

---

apps/blade/src/app/admin/events/_components/events-table.tsx
apps/blade/src/app/admin/events/_components/update-event.tsx
apps/blade/src/app/admin/events/page.tsx
apps/blade/src/app/admin/members/_components/member-profile.tsx
apps/blade/src/app/admin/members/_components/members-table.tsx
apps/blade/src/app/admin/members/_components/scanner.tsx
apps/blade/src/app/admin/members/_components/second-update.tsx
apps/blade/src/app/admin/members/_components/update-member.tsx
apps/blade/src/app/admin/members/page.tsx
apps/blade/src/app/member/application/_components/member-application-form.tsx
apps/blade/src/app/settings/member-profile-form.tsx
packages/api/src/routers/member.ts

phone number was required in application. this was taking too much info from members.
discord field was unnecessary in application
some modals were not responsive
we didn't have an easy way to view member information
changed the phone number field to not be required
discord field removed, pulling from session
modals were made to be responsive
"view profile" button added to member dashboard
pull the changes and locally test by clearing your field in db and reapplying.

fix phone number requirement

---

CONTRIBUTING.md

Instructions for setting up a local database were outdated.
Added instructions for running a local database using the docker file and removed outdated instructions.
Checked how the markdown looks on github:

New local postgres instructions to contributing guide

---

apps/blade/src/app/_components/discord-modal.tsx
apps/blade/src/app/layout.tsx
packages/api/src/routers/auth.ts
packages/api/src/utils.ts
packages/consts/src/knight-hacks.ts

We allow KnightHacks members to be members without joinng the discord but we highly prefer them to be in the discord
Added a dialog box that pesters users to join the Knighthacks discord if they haven't yet

Discord reminder dialog

---

apps/blade/src/app/layout.tsx

Newest build failed
Moved isMember request into a function
pull changes
run pnpm build -F @forge/blade

Put isMember request in RootLayout function

---

apps/blade/src/lib/utils.ts

Dates are in UTC time
Added a 5 hour offset to display EST timezone dates for now
Vibes

Add EST timezone date offset

---

apps/blade/src/lib/utils.ts
apps/tk/src/hooks/animals.ts
apps/tk/src/hooks/daily.ts
apps/tk/src/hooks/reminder.ts

Changes the time zone difference of the VPS to EST so dev times will match prod
We set a new timezone on VPS and Coolify, this PR removes all the - 5 we have been doing to readjust.
Wait til tomorrow...

[Blade] Time Zone Fixes

---

apps/blade/package.json
apps/blade/src/app/admin/events/_components/create-event.tsx
apps/blade/src/app/admin/events/_components/update-event.tsx
apps/blade/src/app/admin/members/_components/member-profile.tsx
apps/blade/src/app/admin/members/_components/scanner.tsx
apps/blade/src/app/dashboard/_components/member-dashboard/member-dashboard.tsx
packages/api/src/routers/event.ts
packages/api/src/routers/member.ts
packages/db/src/schemas/knight-hacks.ts
packages/ui/package.json
packages/ui/src/checkbox.tsx
pnpm-lock.yaml

need to add dues paying events restrictions
added functionality to make events "dues paying" or not
added functionality to restrict non dues paying users to check into dues paying events
**fixed two bugs:**
[BUG] Make links clickable in view member modal
[BUG] when phone number is not entered, field is empty on member dashboard (member profile)
**fixed some uncaught bugs:**
two modals on create event 
premature submission on update event
removed unnecessary event `useEffect` hook
changed calendar component in create/update event as it didn't work in some browsers
type error in event router
pull changes and test
some media to show changes below:
https://github.com/user-attachments/assets/eb2751bd-7c1e-4a79-a9e5-1fc20f54c8b1

dues paying checkin

---

apps/blade/src/app/admin/events/_components/events-table.tsx
apps/blade/src/app/admin/events/_components/view-attendance-button.tsx
apps/blade/src/app/admin/members/_components/member-profile.tsx
packages/api/src/root.ts
packages/api/src/routers/event.ts

Dylan wanted this button
+ getAttendees: this endpoint retrieves the attendees under a specific eventId
+ ViewAttendeesButton: this component acts as a popup that shows all the attendees 
- Removed some DialogContent warnings
**Backend:** 
Tested with Postman
**Frontend:** 
https://github.com/user-attachments/assets/f3b4274a-df1f-4d04-97b2-1f80cd3a3ae8

Added view attendance button, removed some warnings

---

apps/club/src/app/_components/landing/impact-assets/expandable.tsx

Images don't resolve in prod
Casing matters in prod but not in dev so I fixed the image casing
Pull images and run prod build

Fix image issue

---

apps/blade/src/app/sponsor/page.tsx
packages/consts/src/knight-hacks.ts

we needed to update sponsor page
changed sponsor page and added a new youtube link
pull & test

quick sponsor page update

---

apps/blade/package.json
apps/blade/src/app/_components/navigation/reuseable-user-dropdown.tsx
apps/blade/src/app/admin/events/_components/event-details.tsx
apps/blade/src/app/dashboard/_components/member-dashboard/event/event-feedback.tsx
apps/blade/src/app/dashboard/_components/member-dashboard/event/event-showcase.tsx
pnpm-lock.yaml

some issues with ui with events
added padding to event showcase
allowed for event descriptions to parse markdown
changed the position of the feedback button for the most recent event.
responsiveness with event showcasing
add data button to dropdown
pull, test
mobile:

events ui changes

---

apps/tk/src/hooks/reminder.ts

Dates are a day behind in the database because of how we're storing them on blad (We should probably find an actual fix for that soon)
When dates are fetched by the reminders hook 1 is added to them to offset any incorrections
Check the bot channel in the dev disc

reminders webhook bandaid fix (need to revisit)

---

packages/db/src/schemas/knight-hacks.ts

DB was not setup for hackathon registration flow
Added hacker tables and HackerAttendee fields
pushed to my local db to make sure the tables were created with the correct fields

[blade]pre sprint db setup

---

apps/blade/src/app/_components/option-cards.tsx
apps/blade/src/app/_components/user-interface.tsx
apps/blade/src/app/dashboard/_components/hacker-dashboard/hacker-dashboard.tsx
apps/blade/src/app/dashboard/_components/member-dashboard/member-dashboard.tsx
packages/api/src/root.ts
packages/api/src/routers/hacker.ts

- We needed to establish a clear direction on how users interact with the member and hacker dashboard
++ Hacker Router and API: **getHacker** (Retrieves a record of the hacker based off of their profile)
++ Uncommented the old hacker dash lines of code
-- Removed and edited some small stuff
Backend: POSTMAN
Frontend:
https://drive.google.com/file/d/1Klk-eP_R8YeKmEUgHAPXPdzQLIpDtj3r/view?usp=sharing
https://drive.google.com/file/d/16P4qw0ZGtS7V8AvMkeYfuIHSK9MMJ83Q/view?usp=sharing

Hacker Dashboard Flow

---

apps/blade/src/app/_components/email.tsx
apps/blade/src/app/dashboard/page.tsx
apps/blade/src/app/emailTest/page.tsx
packages/api/src/root.ts
packages/api/src/routers/email.ts
packages/api/src/utils.ts

Got to send emails somehow.
Created email router using Google api. 
Successfully sent emails through use of an api call upon loading of dashboard page. 
- Create UI component that takes inputs from text fields & sends emails on the push of a button. 
- Have it not be sent by Dylan's email. (kill dylan bot)
- Integrate email designs made by design team. 
- Figure out how to have multiple recipients of an email.

Blade/emails Email Router 

---

apps/blade/package.json
apps/blade/src/app/admin/banquet-raffle/components/confetti.d.ts
apps/blade/src/app/admin/banquet-raffle/components/raffle-draw.tsx
apps/blade/src/app/admin/banquet-raffle/page.tsx
pnpm-lock.yaml

We need raffle functionality for the Banquet this Saturday based on points.
Creates a raffle tucked away in /admin/banquet-raffle that sources from the amount of points in the Forge database. Then it does some dramatic spinning and beeping til a winner is chosen. I'll delete this once banquet is over :P 
Sending video in discord

[Blade] Banquet Raffle

---

apps/blade/package.json
pnpm-lock.yaml

Forgot to remove a workspace from the blade package
Removed email workspace from blade package.json
run pnpm i

Fixed dependency issue

---

apps/2025/next.config.js

ts extension error when trying to deploy 2025
Fixed the next config
Try to deploy

Fixed next config

---

apps/blade/src/app/dashboard/_components/hacker-dashboard/hacker-data.tsx

the confirm button had to be disabled 
button disabled

most important pr

---

apps/2025/src/app/_components/hero/register-button.tsx
apps/blade/src/app/dashboard/_components/hacker-dashboard/hacker-data.tsx
apps/blade/src/app/hacker/application/_components/hacker-application-form.tsx

Dylan knows
Dylan knows
Dylan knows

2nd Most important pr

---

.env.example
apps/2025/src/app/_components/about/about.tsx
apps/2025/src/app/_components/faq/faq.tsx
apps/2025/src/app/_components/navbar/FloatingNav.tsx
apps/2025/src/app/_components/navbar/MLHBadge.tsx
apps/2025/src/app/_components/navbar/Navbar.tsx
apps/2025/src/app/_components/sponsors/sponsors.tsx
apps/2025/src/app/_components/tracks/tracks.tsx

MY OLD ONE WAS A BRANCH MADE OFF A BRANCH AND I DIDNT REALIZE SO NOW I FIXED IT :D 
The navbar wasn't working on mobile or desktop - buttons were too sensitive and didn't navigate properly. The desktop navbar was hidden at the top of the page, and sections didn't have IDs so navigation couldn't find them.
Fixed desktop navbar to always show and added proper IDs to all sections. Made buttons less sensitive with bigger click areas and better z-index layering. Added smooth scrolling with proper offset and improved mobile menu with click-outside closing.
Tested navigation on desktop and mobile - all buttons now click properly and scroll to correct sections. Verified mobile menu works with touch interactions and desktop navbar is always accessible.

ok now it isnt broken anymore... i think..

---

apps/2025/src/app/_components/faq/faq.tsx
apps/2025/src/app/layout.tsx
apps/2025/src/app/page.tsx

fixed mobile padding

---

apps/blade/src/app/admin/club/data/_components/MemberDemographics.tsx
apps/blade/src/app/admin/club/data/_components/member-data/EngagementInfo.tsx
apps/blade/src/app/admin/club/data/_components/member-data/YearOfStudyPie.tsx
apps/blade/src/app/admin/hackathon/data/_components/ApplicationsOverTimeBarChart.tsx
apps/blade/src/app/admin/hackathon/data/_components/HackathonDataContent.tsx
apps/blade/src/app/admin/hackathon/data/_components/HackerCharts.tsx
apps/blade/src/app/admin/hackathon/data/_components/LevelOfStudyPie.tsx
packages/api/src/routers/hackathon.ts
packages/api/src/routers/hacker.ts
packages/api/src/routers/member.ts
packages/db/src/schemas/knight-hacks.ts

We need observability to the Hackathon Applications, Hackers, and the Club Members. Also info for sponsors
- Adds a year of study to Club & Hack (Freshman, Sophomore, Junior, ...)
- Adds an applications over time field for Hackathons
- Adds more metrics on Club Engagement (Mean, Median, Mode, Q25, Q75, and Q95) for events and point values
peep the heat
engagement
year of study
knighthacks apps
gemiknights apps

[Blade] Better Metrics

---

apps/blade/src/app/_components/navigation/user-qr-code.tsx
apps/blade/src/app/admin/club/data/_components/EventDemographics.tsx
apps/blade/src/app/admin/club/data/_components/HackerEventDemographics.tsx
apps/blade/src/app/admin/club/data/_components/event-data/AttendancesBarChart.tsx
apps/blade/src/app/admin/club/data/_components/event-data/AttendancesMobile.tsx
apps/blade/src/app/admin/club/data/_components/event-data/PopularityRanking.tsx
apps/blade/src/app/admin/club/data/_components/event-data/WeekdayPopularityRadar.tsx
apps/blade/src/app/admin/club/events/_components/create-event.tsx
apps/blade/src/app/admin/club/events/_components/event-details.tsx
apps/blade/src/app/admin/club/events/_components/events-table.tsx
apps/blade/src/app/admin/club/events/_components/update-event.tsx
apps/blade/src/app/admin/club/events/_components/view-attendance-button.tsx
apps/blade/src/app/admin/club/events/page.tsx
apps/blade/src/app/admin/club/members/_components/scanner.tsx
apps/blade/src/app/admin/club/members/page.tsx
apps/blade/src/app/admin/hackathon/data/page.tsx
apps/blade/src/app/dashboard/_components/hacker-dashboard/hacker-qr-button.tsx
packages/api/src/routers/event.ts
packages/api/src/routers/hacker.ts
packages/consts/src/knight-hacks.ts
packages/db/src/schemas/knight-hacks.ts

To make hackathon event management, organization, and analysis smoother.
- Resolved merge conflicts for Luke's work:
- Hacker events added to Blade. They're classified as regular events but tied to a hackathonId. If an event has a hackathon attached, it's hacker only.
- Normal events -> members. Hacker events -> hacker attendees of that hackathon.
- Same event form, plus a hackathon dropdown (defaults to None). Any event tag works if a hackathon is attached.
- Club/Event screen updated for hacker events. Added separate check-in buttons per user type; QR scanners open with their respective event selections.
- The user's QR now visibly indicates hacker vs member to avoid mix ups.
- Club/Data screen now includes hacker events (same DB table) with a checkbox to include/exclude them from …

Hacker Events
